"""Regenerate the compact JIS X 0208 tables embedded in include/rtextjp.h.

The generator uses Python's standard EUC-JP codec only as a row/cell-to-Unicode
mapping. Generated C data has no Python or platform dependency at runtime.
"""

from __future__ import annotations

import argparse
from pathlib import Path


START = "/* RTEXTJP_JIS_TABLES_BEGIN"
END = "/* RTEXTJP_JIS_TABLES_END */"
EXPECTED_COUNTS = {
    "non_kanji": 524,
    "level_1": 2965,
    "level_2": 3390,
}


def decode_row(ku: int) -> list[int]:
    values: list[int] = []
    for ten in range(1, 95):
        encoded = bytes((ku + 0xA0, ten + 0xA0))
        try:
            text = encoded.decode("euc_jp")
        except UnicodeDecodeError:
            continue
        if len(text) != 1:
            raise RuntimeError(f"unexpected mapping at ku={ku}, ten={ten}: {text!r}")
        values.append(ord(text))
    return values


def format_table(name: str, rows: range) -> tuple[str, int]:
    parts = [f"static const unsigned short rtextjp_jis_{name}[] = {{"]
    count = 0
    for ku in rows:
        values = decode_row(ku)
        if not values:
            continue
        parts.append(f"    /* ku {ku:02d} */")
        for offset in range(0, len(values), 10):
            chunk = values[offset : offset + 10]
            parts.append("    " + ", ".join(f"0x{value:04X}" for value in chunk) + ",")
        count += len(values)
    parts.append("};")
    return "\n".join(parts), count


def generated_block() -> str:
    definitions: list[str] = []
    specifications = (
        ("non_kanji", range(1, 16)),
        ("level_1", range(16, 48)),
        ("level_2", range(48, 85)),
    )
    total = 0
    all_values: set[int] = set()
    for name, rows in specifications:
        definition, count = format_table(name, rows)
        if count != EXPECTED_COUNTS[name]:
            raise RuntimeError(f"{name}: expected {EXPECTED_COUNTS[name]}, got {count}")
        definitions.append(definition)
        total += count
        for ku in rows:
            all_values.update(decode_row(ku))

    if total != 6879 or len(all_values) != 6879:
        raise RuntimeError(f"expected 6,879 unique JIS X 0208 mappings, got {len(all_values)}")

    return (
        f"{START}\n"
        " * Generated by tools/generate_jis_tables.py. Do not edit this block by hand.\n"
        " * JIS X 0208: 524 non-kanji, 2,965 level-1, 3,390 level-2 mappings.\n"
        " */\n"
        + "\n\n".join(definitions)
        + f"\n{END}"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the embedded data is stale")
    parser.add_argument(
        "--header",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "include" / "rtextjp.h",
    )
    args = parser.parse_args()

    header = args.header.resolve()
    original = header.read_text(encoding="utf-8")
    start = original.index(START)
    end = original.index(END, start) + len(END)
    updated = original[:start] + generated_block() + original[end:]

    if args.check:
        if updated != original:
            raise SystemExit("embedded JIS tables are stale; run this script without --check")
        print("embedded JIS tables are current")
        return 0

    header.write_text(updated, encoding="utf-8", newline="\n")
    print(f"updated {header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
